appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: pYU8ZQCebsTQoVzdMtExZq9o2hcOdfUC7OKJJDyWhNFaQuhoJ0PcBaQ1y4ZIaFaeeGpggHknDPXjy7jjAWQNEx+DGRGtnDwqcvhDBapfIMtvJSNKXHPxsthwQi9IWDWXzXBCIzvYGnkhAr9iiKcMdLQtMUI2epkJZJXpZrn6aKrMtKMFoCR2dvsDov75TwF9Sd0V6KeNPqkm0e52/c81msIpIAjO9Gl9J58PconE7supuFY4qiZkI2incpj0op6Tbm3jS4DeHEXLyNzvifXvIoOgXfwIzNlIB4gSnM8aIRnhukbcYm/Ccr+gBqpNmz9KuO/taAtVPyuRMl6M8potC/E3d3zM9OVcWxVgfmpLSs3nCQg84epOz5aTDZhY5kcG4wH3QFBCdINcHEGJU2w0GOb8A+93cQC2onEVN8a1AlMHjJNb/C0ZhdH5FCrjIKg4/0ePs1LQPCDK9RBuEk61RszJocx9Zy1pOA/cmgA4iopPuXAsKg66pc2Uj8kQwdu+jv8HjUxYh1BlODxlHIBSkOpL1fq52sfjCOHnFRx7EJwqrRClyafi41t4omQB+BerSON3tNvggU2h2NxZnpBB/oVBFzyGXcVQ3WVF7okGuBx/ruZXTld/eEniOqPzb0I524ChDIuIomMnWwd8vJ/xUuTcVu9V03m2W5r3ioagFjM=}
bot:
  automerge: true
